/**
 * Builds a file matching Google's disavow links format exactly:
 * https://search.google.com/search-console/disavow-links
 *
 * Rule of thumb (matches common practice): if 3+ toxic links come from
 * the same source domain, disavow the whole domain (`domain:example.com`)
 * rather than listing every single URL - cleaner file, same effect.
 * Otherwise disavow the specific URLs individually.
 */
function generateDisavowFile(toxicLinks) {
  const byDomain = {};
  toxicLinks.forEach((link) => {
    const domain = link.source_domain || 'unknown-domain';
    if (!byDomain[domain]) byDomain[domain] = [];
    byDomain[domain].push(link.source_url);
  });

  const lines = [
    '# Disavow file generated by CORTEX - review before uploading to Google Search Console',
    `# Generated: ${new Date().toISOString()}`,
    `# Total toxic links reviewed: ${toxicLinks.length}`,
    '',
  ];

  for (const [domain, urls] of Object.entries(byDomain)) {
    if (urls.length >= 3) {
      lines.push(`domain:${domain}`);
    } else {
      urls.forEach((url) => lines.push(url));
    }
  }

  return lines.join('\n');
}

module.exports = { generateDisavowFile };
