const PDFDocument = require('pdfkit');

/**
 * Builds a branded PDF report from data already collected by every
 * other module - this file only lays it out. The caller (reporting
 * controller) is responsible for gathering the actual numbers from
 * Content/AEO/Backlink/Keyword/Competitor services; this keeps report
 * layout logic and data-gathering logic cleanly separated.
 *
 * @param {object} report
 * @param {object} report.site - { domain, display_name }
 * @param {object} report.branding - { companyName, primaryColorHex? }
 * @param {object} report.auditSummary - from crawl.controller's getAuditSummary shape
 * @param {object} report.backlinkSummary - from backlink.controller's getBacklinkSummary shape
 * @param {object[]} report.rankHistory - [{ keyword, position, checked_at }]
 * @param {object[]} report.citationSummary - from citationTracker's getCitationShareOfVoice shape
 * @returns {Promise<Buffer>}
 */
function buildSiteReportPdf(report) {
  return new Promise((resolve, reject) => {
    const { site, branding = {}, auditSummary, backlinkSummary, rankHistory = [], citationSummary = [] } = report;
    const primaryColor = branding.primaryColorHex || '#0F9C8F';

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // --- Header ---
    doc.fillColor(primaryColor).fontSize(22).text(branding.companyName || 'CORTEX SEO Report', { align: 'left' });
    doc.fillColor('#333333').fontSize(12).text(`${site.display_name || site.domain} (${site.domain})`);
    doc.fontSize(9).fillColor('#888888').text(`Generated: ${new Date().toLocaleDateString()}`);
    doc.moveDown(1.5);

    // --- Site Health / Audit ---
    doc.fillColor(primaryColor).fontSize(14).text('Site Health');
    doc.moveDown(0.3);
    if (auditSummary && auditSummary.totalPages > 0) {
      doc.fillColor('#333333').fontSize(11);
      doc.text(`Health Score: ${auditSummary.healthScore}/100`);
      doc.text(`Pages Crawled: ${auditSummary.totalPages}`);
      Object.entries(auditSummary.issues || {}).forEach(([issue, count]) => {
        doc.text(`  - ${formatLabel(issue)}: ${count}`);
      });
    } else {
      doc.fillColor('#888888').fontSize(11).text('No crawl data available yet.');
    }
    doc.moveDown(1);

    // --- Rank History Summary ---
    doc.fillColor(primaryColor).fontSize(14).text('Keyword Rankings (recent checks)');
    doc.moveDown(0.3);
    doc.fillColor('#333333').fontSize(10);
    if (rankHistory.length > 0) {
      rankHistory.slice(0, 20).forEach((r) => {
        doc.text(`${r.keyword} - position ${r.position ?? 'not ranked'} (${new Date(r.checked_at).toLocaleDateString()})`);
      });
    } else {
      doc.fillColor('#888888').text('No rank history yet.');
    }
    doc.moveDown(1);

    // --- Backlink Summary ---
    doc.fillColor(primaryColor).fontSize(14).text('Backlink Profile');
    doc.moveDown(0.3);
    doc.fillColor('#333333').fontSize(11);
    if (backlinkSummary) {
      doc.text(`Referring Domains: ${backlinkSummary.referringDomains}`);
      doc.text(`Active Links: ${backlinkSummary.totalActiveLinks}`);
      doc.text(`Toxic Links Flagged: ${backlinkSummary.totalToxicLinks}`);
      doc.text(`Lost Links: ${backlinkSummary.totalLostLinks}`);
    } else {
      doc.fillColor('#888888').text('No backlink data available yet.');
    }
    doc.moveDown(1);

    // --- AI Citation Share of Voice ---
    doc.fillColor(primaryColor).fontSize(14).text('AI Answer Engine Visibility (AEO/GEO)');
    doc.moveDown(0.3);
    doc.fillColor('#333333').fontSize(11);
    if (citationSummary.length > 0) {
      citationSummary.forEach((c) => {
        doc.text(`${formatLabel(c.engine)}: cited in ${c.citationRate}% of checks (${c.citedCount}/${c.totalChecks})`);
      });
    } else {
      doc.fillColor('#888888').text('No citation checks run yet.');
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999999').text(
      'This report was generated by CORTEX from data collected across your connected modules. Traffic and forecast figures elsewhere in this platform are estimates, not guarantees.',
      { align: 'left' }
    );

    doc.end();
  });
}

function formatLabel(key) {
  return key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase()).trim();
}

module.exports = { buildSiteReportPdf };
